{
 "title": "SLO Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\nsum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\"}[5m])) by (le, verb))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\",code=~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(apiserver_request_total{job=\"apiserver\",code!~\"5..\"}[2d]))\n/\nsum (rate(apiserver_request_total{job=\"apiserver\"}[2d]))"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((1 - (sum(increase(apiserver_request_total{job=\"apiserver\", code=\"200\"}[7d])) by (verb)) / sum(increase(apiserver_request_total{job=\"apiserver\"}[7d])) by (verb)) / (1 - .90))"
    }
   ]
  }
 ]
}